version: '3'

services:
  rabbitmq:
    restart: always
    image: "rabbitmq:3-management-alpine"
    hostname: "${RABBITMQ_HOSTNAME}"
    env_file:
      - ./.env.rabbitmq
    ports:
      - "${RABBITMQ_EXPOSE_PORT}:5672"
      - "${RABBITMQ_MGR_EXPOSE_PORT}:15672"
    volumes:
      - data-rabbitmq:/var/lib/rabbitmq

volumes:
  data-rabbitmq:
    driver: local
